var annotated_dup =
[
    [ "audio_manager", "structaudio__manager.html", "structaudio__manager" ],
    [ "band_s", "structband__s.html", "structband__s" ],
    [ "bitreenode_s", "structbitreenode__s.html", "structbitreenode__s" ],
    [ "circle_s", "structcircle__s.html", "structcircle__s" ],
    [ "entity_s", "structentity__s.html", "structentity__s" ],
    [ "EntityManager", "struct_entity_manager.html", "struct_entity_manager" ],
    [ "graph_s", "structgraph__s.html", "structgraph__s" ],
    [ "Graphics", "struct_graphics.html", "struct_graphics" ],
    [ "graphnode_s", "structgraphnode__s.html", "structgraphnode__s" ],
    [ "guimanager_s", "structguimanager__s.html", "structguimanager__s" ],
    [ "guiwindow_s", "structguiwindow__s.html", "structguiwindow__s" ],
    [ "Node_S", "struct_node___s.html", "struct_node___s" ],
    [ "priorityqueue", "structpriorityqueue.html", "structpriorityqueue" ],
    [ "rect_s", "structrect__s.html", "structrect__s" ],
    [ "sound_s", "structsound__s.html", "structsound__s" ],
    [ "Sprite_S", "struct_sprite___s.html", "struct_sprite___s" ],
    [ "SpriteManager", "struct_sprite_manager.html", "struct_sprite_manager" ],
    [ "Student", "struct_student.html", "struct_student" ],
    [ "textdisplay_s", "structtextdisplay__s.html", "structtextdisplay__s" ],
    [ "textmanager_s", "structtextmanager__s.html", "structtextmanager__s" ],
    [ "think_function", "structthink__function.html", "structthink__function" ],
    [ "tile_s", "structtile__s.html", "structtile__s" ],
    [ "tilemap_s", "structtilemap__s.html", "structtilemap__s" ],
    [ "Vector2D", "struct_vector2_d.html", "struct_vector2_d" ],
    [ "Vector3D", "struct_vector3_d.html", "struct_vector3_d" ],
    [ "Vector4D", "struct_vector4_d.html", "struct_vector4_d" ]
];